# docker compose -f docker-compose-single.yml up -d
# docker compose -f docker-compose-single.yml down

version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
#    restart: unless-stopped
    restart: always
    hostname: zookeeper
    container_name: kafka-zookeeper
    volumes:
#      - ./data:/data
      - /etc/localtime:/etc/localtime
    ports:
      - 2181:2181

  kafka:
#    image: wurstmeister/kafka:1.0.0
    image: wurstmeister/kafka
    restart: always
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "netmusic"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫netmusic的topic
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181/kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
#      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
#      - ./kafka-logs:/kafka
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

#networks:
#  default:
#    external:
#      name: es-network
