/*
 Navicat Premium Data Transfer

 Source Server         : zjmsg@20.26.24.150
 Source Server Type    : Oracle
 Source Server Version : 120100
 Source Host           : 20.26.24.150:1521
 Source Schema         : ZJMSG

 Target Server Type    : Oracle
 Target Server Version : 120100
 File Encoding         : 65001

 Date: 26/06/2018 17:04:36
*/


-- ----------------------------
-- Table structure for CFG_ID_GENERATOR
-- ----------------------------
DROP TABLE "ZJMSG"."CFG_ID_GENERATOR";
CREATE TABLE "ZJMSG"."CFG_ID_GENERATOR" (
  "TABLE_NAME" NVARCHAR2(100) VISIBLE NOT NULL ,
  "DOMAIN_ID" NUMBER VISIBLE NOT NULL ,
  "GENERATOR_TYPE" NCHAR(1) VISIBLE NOT NULL ,
  "SEQUENCE_NAME" NVARCHAR2(60) VISIBLE ,
  "MAX_ID" NUMBER VISIBLE ,
  "START_VALUE" NUMBER VISIBLE ,
  "MIN_VALUE" NUMBER VISIBLE ,
  "MAX_VALUE" NUMBER VISIBLE ,
  "INCREMENT_VALUE" NUMBER VISIBLE ,
  "CYCLE_FLAG" NCHAR(1) VISIBLE ,
  "CACHE_SIZE" NUMBER VISIBLE ,
  "SEQUENCE_CREATE_SCRIPT" NCLOB VISIBLE ,
  "HIS_TABLE_NAME" NVARCHAR2(100) VISIBLE ,
  "HIS_SEQUENCE_NAME" NVARCHAR2(60) VISIBLE ,
  "HIS_DATA_FLAG" NCHAR(1) VISIBLE ,
  "HIS_MAX_ID" NUMBER VISIBLE ,
  "HIS_DONECODE_FLAG" NCHAR(1) VISIBLE ,
  "STEP_BY" NUMBER VISIBLE ,
  "HIS_STEP_BY" NUMBER VISIBLE 
)
TABLESPACE "TEST_DATA"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CFG_ID_GENERATOR
-- ----------------------------
INSERT INTO "ZJMSG"."CFG_ID_GENERATOR" VALUES ('MSG_EXAMINE_PRODUCER', '1', 'S', 'SEQ_MSG_EXAMINE_PRODUCER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "ZJMSG"."CFG_ID_GENERATOR" VALUES ('MSG_EXAMINE_CONSUMER', '1', 'S', 'SEQ_MSG_EXAMINE_CONSUMER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
COMMIT;

-- ----------------------------
-- Primary Key structure for table CFG_ID_GENERATOR
-- ----------------------------
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401493" PRIMARY KEY ("TABLE_NAME");

-- ----------------------------
-- Checks structure for table CFG_ID_GENERATOR
-- ----------------------------
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401392" CHECK (TABLE_NAME IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401393" CHECK (DOMAIN_ID IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401394" CHECK (GENERATOR_TYPE IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401724" CHECK ("TABLE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401725" CHECK ("DOMAIN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZJMSG"."CFG_ID_GENERATOR" ADD CONSTRAINT "SYS_C00401726" CHECK ("GENERATOR_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
COMMIT;
